
CREATE OR REPLACE WAREHOUSE HYBRID_SCD_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE RETAIL_HYBRID_DB;
CREATE OR REPLACE SCHEMA RETAIL_HYBRID_DB.HYBRID_SCHEMA;

USE WAREHOUSE HYBRID_SCD_WH;
USE DATABASE RETAIL_HYBRID_DB;
USE SCHEMA HYBRID_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE HYBRID_STAGE
    FILE_FORMAT = CSV_FORMAT;



CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30));

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE);

COPY INTO STG_CUSTOMERS_INITIAL 
FROM @HYBRID_STAGE/customers_initial.csv 
FILE_FORMAT = CSV_FORMAT 
FORCE = TRUE;

COPY INTO STG_CUSTOMER_UPDATES 
FROM @HYBRID_STAGE/customers_updates.csv 
FILE_FORMAT = CSV_FORMAT 
ON_ERROR=CONTINUE;



CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN);



INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, 
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, 
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    NULL AS PREVIOUS_CITY, 
    STATE, 
    MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    NULL AS PREVIOUS_MEMBERSHIP, 
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP, 
    SEGMENT, 
    '2026-01-01'::DATE AS EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMERS_INITIAL;



SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    PREVIOUS_CITY, 
    STATE, 
    CURRENT_MEMBERSHIP, 
    PREVIOUS_MEMBERSHIP, 
    HISTORICAL_MEMBERSHIP, 
    SEGMENT, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE, 
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID;


-- APPLY HYBRID UPDATES FOR CUSTOMERS 101, 103, AND 104


UPDATE DIM_CUSTOMER_HYBRID target
SET 
    target.EXPIRY_DATE = DATEADD(DAY, -1, source.EFFECTIVE_DATE),
    target.IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES source
WHERE target.CUSTOMER_ID = source.CUSTOMER_ID
  AND target.IS_CURRENT = TRUE;

-- Step 2: Insert new active versions
INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, 
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, 
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    u.CUSTOMER_ID, 
    u.CUSTOMER_NAME, 
    u.CITY, 
    d.CITY AS PREVIOUS_CITY, 
    u.STATE, 
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    d.HISTORICAL_MEMBERSHIP AS PREVIOUS_MEMBERSHIP, 
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP, 
    u.SEGMENT, 
    u.EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_HYBRID d ON u.CUSTOMER_ID = d.CUSTOMER_ID AND d.IS_CURRENT = FALSE;

-- Step 3: Synchronize global current & prior attributes (City, State, Current/Previous Membership) across all records
UPDATE DIM_CUSTOMER_HYBRID target
SET 
    target.CITY = source.CITY,
    target.PREVIOUS_CITY = CASE 
        WHEN source.CITY != target.CITY OR target.PREVIOUS_CITY IS NULL 
        THEN target.CITY 
        ELSE target.PREVIOUS_CITY 
    END,
    target.STATE = source.STATE,
    target.CURRENT_MEMBERSHIP = source.CURRENT_MEMBERSHIP,
    target.PREVIOUS_MEMBERSHIP = source.PREVIOUS_MEMBERSHIP
FROM (
    SELECT 
        CUSTOMER_ID, 
        CITY, 
        STATE, 
        CURRENT_MEMBERSHIP, 
        PREVIOUS_MEMBERSHIP 
    FROM DIM_CUSTOMER_HYBRID 
    WHERE IS_CURRENT = TRUE
) source
WHERE target.CUSTOMER_ID = source.CUSTOMER_ID;


--  DISPLAY COMPLETE DIMENSION HISTORY
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    PREVIOUS_CITY, 
    STATE, 
    CURRENT_MEMBERSHIP, 
    PREVIOUS_MEMBERSHIP, 
    HISTORICAL_MEMBERSHIP, 
    SEGMENT, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE, 
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- DISPLAY ACTIVE CUSTOMER REPORT
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    PREVIOUS_CITY, 
    STATE, 
    CURRENT_MEMBERSHIP, 
    PREVIOUS_MEMBERSHIP, 
    SEGMENT
FROM DIM_CUSTOMER_HYBRID
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


-- POINT-IN-TIME HISTORICAL QUERY (AS OF MARCH 15, 2026)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    HISTORICAL_MEMBERSHIP, 
    SEGMENT, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE
FROM DIM_CUSTOMER_HYBRID
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


-- METRIC VALIDATION AND RECORD COUNTS
SELECT 'TOTAL RECORD COUNT' AS METRIC, COUNT(*) AS VALUE 
FROM DIM_CUSTOMER_HYBRID
UNION ALL
SELECT 'CURRENT RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_HYBRID 
WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_HYBRID 
WHERE IS_CURRENT = FALSE;