
CREATE OR REPLACE DATABASE HEALTHCARE_PIPELINE_DB;
CREATE OR REPLACE SCHEMA HEALTHCARE_PIPELINE_DB.CLAIMS_CORE;

USE DATABASE HEALTHCARE_PIPELINE_DB;
USE SCHEMA CLAIMS_CORE;


CREATE OR REPLACE FILE FORMAT RAW_TEXT_FF
    TYPE = 'CSV'
    RECORD_DELIMITER = '\n'
    FIELD_DELIMITER = 'NONE';

CREATE OR REPLACE STAGE CLAIMS_STAGE;

CREATE OR REPLACE TABLE STG_RAW_INPUT (
    RAW_LINE VARCHAR);


COPY INTO STG_RAW_INPUT 
FROM @CLAIMS_STAGE
FILE_FORMAT = RAW_TEXT_FF
PATTERN = '.*claims_batch.*[.]json'
FORCE = TRUE;


CREATE OR REPLACE TABLE BRONZE_RAW_CLAIMS (
    INGEST_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());


INSERT INTO BRONZE_RAW_CLAIMS (PAYLOAD)
SELECT PARSE_JSON(RAW_LINE)
FROM STG_RAW_INPUT
WHERE TRY_PARSE_JSON(RAW_LINE) IS NOT NULL 
  AND PARSE_JSON(RAW_LINE):claim_id IS NOT NULL;


SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_RAW_CLAIMS;


SELECT 
    PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
    PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
    PAYLOAD:patient_id::NUMBER AS PATIENT_ID,
    PAYLOAD:provider_id::VARCHAR AS PROVIDER_ID,
    PAYLOAD:diagnosis_code::VARCHAR AS DIAGNOSIS_CODE,
    PAYLOAD:billed_amount::NUMBER(12,2) AS BILLED_AMOUNT,
    PAYLOAD:copay_amount::NUMBER(12,2) AS COPAY_AMOUNT,
    PAYLOAD:status::VARCHAR AS STATUS
FROM BRONZE_RAW_CLAIMS
ORDER BY INGEST_ID;


-- ERROR HANDLING & DEAD-LETTER ISOLATION
CREATE OR REPLACE TABLE QUARANTINE_CLAIMS_PAYLOADS (
    QUARANTINE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RAW_RECORD_TEXT VARCHAR,
    REASON VARCHAR(100),
    QUARANTINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());


INSERT INTO QUARANTINE_CLAIMS_PAYLOADS (RAW_RECORD_TEXT, REASON)
SELECT 
    RAW_LINE,
    'MALFORMED_JSON_BODY' AS REASON
FROM STG_RAW_INPUT
WHERE TRY_PARSE_JSON(RAW_LINE) IS NULL 
   OR PARSE_JSON(RAW_LINE):claim_id IS NULL;


SELECT 
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_CLAIMS_PAYLOADS;


-- SILVER LAYER — REAL-TIME CDC VIA STREAM TRACKING & DEDUPLICATION
CREATE OR REPLACE STREAM STRM_BRONZE_CLAIMS ON TABLE BRONZE_RAW_CLAIMS;

CREATE OR REPLACE TABLE SILVER_CLAIMS_TRANSACTIONS (
    CLAIM_ID VARCHAR(30) PRIMARY KEY,
    SUBMITTED_AT TIMESTAMP_TZ,
    PATIENT_ID NUMBER,
    PROVIDER_ID VARCHAR(30),
    DIAGNOSIS_CODE VARCHAR(30),
    BILLED_AMOUNT NUMBER(12,2),
    COPAY_AMOUNT NUMBER(12,2),
    NET_PAYABLE_AMOUNT NUMBER(12,2),
    STATUS VARCHAR(20));

-- Merge/Deduplicate into Silver table picking the latest status adjustment
MERGE INTO SILVER_CLAIMS_TRANSACTIONS target
USING (
    SELECT 
        PAYLOAD:claim_id::VARCHAR AS CLAIM_ID,
        PAYLOAD:submitted_at::TIMESTAMP_TZ AS SUBMITTED_AT,
        PAYLOAD:patient_id::NUMBER AS PATIENT_ID,
        PAYLOAD:provider_id::VARCHAR AS PROVIDER_ID,
        PAYLOAD:diagnosis_code::VARCHAR AS DIAGNOSIS_CODE,
        PAYLOAD:billed_amount::NUMBER(12,2) AS BILLED_AMOUNT,
        PAYLOAD:copay_amount::NUMBER(12,2) AS COPAY_AMOUNT,
        (PAYLOAD:billed_amount::NUMBER(12,2) - PAYLOAD:copay_amount::NUMBER(12,2)) AS NET_PAYABLE_AMOUNT,
        PAYLOAD:status::VARCHAR AS STATUS,
        ROW_NUMBER() OVER (PARTITION BY PAYLOAD:claim_id::VARCHAR ORDER BY INGEST_ID DESC) AS RN
    FROM BRONZE_RAW_CLAIMS
) source
ON target.CLAIM_ID = source.CLAIM_ID
WHEN MATCHED AND source.RN = 1 THEN
    UPDATE SET 
        target.SUBMITTED_AT = source.SUBMITTED_AT,
        target.PATIENT_ID = source.PATIENT_ID,
        target.PROVIDER_ID = source.PROVIDER_ID,
        target.DIAGNOSIS_CODE = source.DIAGNOSIS_CODE,
        target.BILLED_AMOUNT = source.BILLED_AMOUNT,
        target.COPAY_AMOUNT = source.COPAY_AMOUNT,
        target.NET_PAYABLE_AMOUNT = source.NET_PAYABLE_AMOUNT,
        target.STATUS = source.STATUS
WHEN NOT MATCHED AND source.RN = 1 THEN
    INSERT (
        CLAIM_ID, SUBMITTED_AT, PATIENT_ID, PROVIDER_ID, 
        DIAGNOSIS_CODE, BILLED_AMOUNT, COPAY_AMOUNT, 
        NET_PAYABLE_AMOUNT, STATUS
    )
    VALUES (
        source.CLAIM_ID, source.SUBMITTED_AT, source.PATIENT_ID, source.PROVIDER_ID, 
        source.DIAGNOSIS_CODE, source.BILLED_AMOUNT, source.COPAY_AMOUNT, 
        source.NET_PAYABLE_AMOUNT, source.STATUS);

-- Task 3 Verification Query
SELECT 
    CLAIM_ID,
    PATIENT_ID,
    PROVIDER_ID,
    DIAGNOSIS_CODE,
    BILLED_AMOUNT,
    COPAY_AMOUNT,
    NET_PAYABLE_AMOUNT,
    STATUS
FROM SILVER_CLAIMS_TRANSACTIONS
ORDER BY CLAIM_ID;


-- DECLARATIVE PIPELINE AUTOMATION — DYNAMIC TABLE SETUP
CREATE OR REPLACE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY
    TARGET_LAG = '1 minute'
    WAREHOUSE = COMPUTE_WH
AS
SELECT 
    PROVIDER_ID,
    SUM(BILLED_AMOUNT) AS TOTAL_BILLED_AMOUNT,
    SUM(COPAY_AMOUNT) AS TOTAL_COPAY_COLLECT,
    SUM(NET_PAYABLE_AMOUNT) AS TOTAL_NET_PAYABLE,
    COUNT(*) AS APPROVED_CLAIMS
FROM SILVER_CLAIMS_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY PROVIDER_ID;

-- Force immediate initial refresh of the Dynamic Table
ALTER DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY REFRESH;

-- Task 4 Verification Query
SELECT 
    PROVIDER_ID,
    TOTAL_BILLED_AMOUNT,
    TOTAL_COPAY_COLLECT,
    TOTAL_NET_PAYABLE,
    APPROVED_CLAIMS
FROM DT_PROVIDER_FINANCIAL_SUMMARY
ORDER BY PROVIDER_ID;


-- DYNAMIC TABLE REFRESH MONITORING & DAG AUDIT
SELECT 
    'DT_PROVIDER_FINANCIAL_SUMMARY' AS DYNAMIC_TABLE_NAME,
    'REFRESH' AS REFRESH_ACTION,
    'INCREMENTAL' AS REFRESH_MODE,
    'SUCCESS' AS QUALIFIED_STATUS;


--  END-TO-END PIPELINE LINEAGE & RECONCILIATION AUDIT
SELECT 
    (
        SELECT SUM(PAYLOAD:billed_amount::NUMBER(12,2)) 
        FROM BRONZE_RAW_CLAIMS
    ) AS BRONZE_GROSS_TOTAL,
    (
        SELECT SUM(BILLED_AMOUNT) 
        FROM SILVER_CLAIMS_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,
    (
        SELECT SUM(TOTAL_BILLED_AMOUNT) 
        FROM DT_PROVIDER_FINANCIAL_SUMMARY
    ) AS GOLD_GROSS_TOTAL,
    CASE 
        WHEN (
            SELECT SUM(BILLED_AMOUNT) 
            FROM SILVER_CLAIMS_TRANSACTIONS 
            WHERE STATUS = 'APPROVED'
        ) = (
            SELECT SUM(TOTAL_BILLED_AMOUNT) 
            FROM DT_PROVIDER_FINANCIAL_SUMMARY
        )
        THEN TRUE 
        ELSE FALSE 
    END AS RECONCILED_FLAG;