
CREATE OR REPLACE DATABASE LOGISTICS_LAKEHOUSE_DB;
CREATE OR REPLACE SCHEMA LOGISTICS_LAKEHOUSE_DB.FLEET_CORE;

USE DATABASE LOGISTICS_LAKEHOUSE_DB;
USE SCHEMA FLEET_CORE;


CREATE OR REPLACE FILE FORMAT JSON_FF
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE;


CREATE OR REPLACE FILE FORMAT RAW_TEXT_FF
    TYPE = 'CSV'
    RECORD_DELIMITER = '\n'
    FIELD_DELIMITER = 'NONE';


CREATE OR REPLACE STAGE IOT_STAGE;


CREATE OR REPLACE TABLE STG_RAW_INPUT (
    RAW_LINE VARCHAR);


COPY INTO STG_RAW_INPUT 
FROM @IOT_STAGE
FILE_FORMAT = RAW_TEXT_FF
PATTERN = '.*iot_telematics_batch.*[.]json'
FORCE = TRUE;


CREATE OR REPLACE TABLE BRONZE_IOT_STREAMS (
    INGEST_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RAW_PAYLOAD VARIANT,
    RECORDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());


INSERT INTO BRONZE_IOT_STREAMS (RAW_PAYLOAD)
SELECT PARSE_JSON(RAW_LINE)
FROM STG_RAW_INPUT
WHERE TRY_PARSE_JSON(RAW_LINE) IS NOT NULL 
  AND PARSE_JSON(RAW_LINE):payload_id IS NOT NULL;


SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_IOT_STREAMS;


SELECT 
    RAW_PAYLOAD:payload_id::VARCHAR AS PAYLOAD_ID,
    RAW_PAYLOAD:payload_type::VARCHAR AS PAYLOAD_TYPE,
    RAW_PAYLOAD:timestamp::TIMESTAMP_TZ AS EVENT_TIME,
    RAW_PAYLOAD:data.vehicle_id::VARCHAR AS VEHICLE_ID,
    RAW_PAYLOAD:data.declared_value::NUMBER(12,2) AS DECLARED_VALUE
FROM BRONZE_IOT_STREAMS
ORDER BY PAYLOAD_ID;



CREATE OR REPLACE TABLE QUARANTINE_IOT_PAYLOADS (
    QUARANTINE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RAW_RECORD_TEXT VARCHAR,
    REASON VARCHAR(100),
    QUARANTINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());


INSERT INTO QUARANTINE_IOT_PAYLOADS (RAW_RECORD_TEXT, REASON)
SELECT 
    RAW_LINE,
    'MALFORMED_JSON_BODY' AS REASON
FROM STG_RAW_INPUT
WHERE TRY_PARSE_JSON(RAW_LINE) IS NULL 
   OR PARSE_JSON(RAW_LINE):payload_id IS NULL;


SELECT 
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_IOT_PAYLOADS;


--SILVER LAYER ETL — SCHEMA-ON-WRITE MODELING & COMPUTATIONS
CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE (
    SHIPMENT_ID VARCHAR(30) PRIMARY KEY,
    PAYLOAD_ID VARCHAR(30),
    VEHICLE_ID VARCHAR(30),
    DESTINATION_COUNTRY VARCHAR(10),
    DECLARED_VALUE NUMBER(12,2),
    DUTY_PCT NUMBER(5,2),
    DUTY_AMOUNT_DUE NUMBER(12,2),
    BORDER_CODE VARCHAR(50),
    CLEARANCE_STATUS VARCHAR(30));

INSERT INTO SILVER_CUSTOMS_CLEARANCE (
    SHIPMENT_ID,
    PAYLOAD_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS)
SELECT 
    RAW_PAYLOAD:data.shipment_id::VARCHAR AS SHIPMENT_ID,
    RAW_PAYLOAD:payload_id::VARCHAR AS PAYLOAD_ID,
    RAW_PAYLOAD:data.vehicle_id::VARCHAR AS VEHICLE_ID,
    RAW_PAYLOAD:data.destination_country::VARCHAR AS DESTINATION_COUNTRY,
    RAW_PAYLOAD:data.declared_value::NUMBER(12,2) AS DECLARED_VALUE,
    RAW_PAYLOAD:data.duty_pct::NUMBER(5,2) AS DUTY_PCT,
    ROUND(
        RAW_PAYLOAD:data.declared_value::NUMBER(12,2) * (RAW_PAYLOAD:data.duty_pct::NUMBER(5,2) / 100.0), 
        2
    ) AS DUTY_AMOUNT_DUE,
    RAW_PAYLOAD:data.border_clearance_code::VARCHAR AS BORDER_CODE,
    RAW_PAYLOAD:data.clearance_status::VARCHAR AS CLEARANCE_STATUS
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS';


SELECT 
    SHIPMENT_ID,
    VEHICLE_ID,
    DESTINATION_COUNTRY AS DEST_COUNTRY,
    DECLARED_VALUE,
    DUTY_PCT,
    DUTY_AMOUNT_DUE,
    BORDER_CODE,
    CLEARANCE_STATUS
FROM SILVER_CUSTOMS_CLEARANCE
ORDER BY SHIPMENT_ID;


-- GOLD LAYER STRATEGIC AGGREGATIONS
CREATE OR REPLACE TABLE GOLD_COUNTRY_DUTY_SUMMARY (
    DESTINATION_COUNTRY VARCHAR(10) PRIMARY KEY,
    TOTAL_CLEARED_VAL NUMBER(12,2),
    TOTAL_DUTIES_COLLECTED NUMBER(12,2),
    AVG_DUTY_RATE_PCT NUMBER(5,2),
    CLEARED_SHIPMENTS NUMBER);

INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY (
    DESTINATION_COUNTRY,
    TOTAL_CLEARED_VAL,
    TOTAL_DUTIES_COLLECTED,
    AVG_DUTY_RATE_PCT,
    CLEARED_SHIPMENTS)
SELECT 
    DESTINATION_COUNTRY,
    SUM(DECLARED_VALUE) AS TOTAL_CLEARED_VAL,
    SUM(DUTY_AMOUNT_DUE) AS TOTAL_DUTIES_COLLECTED,
    ROUND(AVG(DUTY_PCT), 2) AS AVG_DUTY_RATE_PCT,
    COUNT(*) AS CLEARED_SHIPMENTS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'
GROUP BY DESTINATION_COUNTRY;


SELECT 
    DESTINATION_COUNTRY AS DEST_COUNTRY,
    TOTAL_CLEARED_VAL,
    TOTAL_DUTIES_COLLECTED,
    AVG_DUTY_RATE_PCT,
    CLEARED_SHIPMENTS
FROM GOLD_COUNTRY_DUTY_SUMMARY
ORDER BY DESTINATION_COUNTRY;


-- DISASTER RECOVERY VIA SNOWFLAKE TIME-TRAVEL AUDITING
UPDATE SILVER_CUSTOMS_CLEARANCE 
SET CLEARANCE_STATUS = 'REJECTED' 
WHERE DESTINATION_COUNTRY = 'CAN';


SELECT 
    SHIPMENT_ID,
    DESTINATION_COUNTRY,
    CLEARANCE_STATUS 
FROM SILVER_CUSTOMS_CLEARANCE BEFORE (STATEMENT => LAST_QUERY_ID())
WHERE DESTINATION_COUNTRY = 'CAN';


UPDATE SILVER_CUSTOMS_CLEARANCE 
SET CLEARANCE_STATUS = 'CLEARED'
WHERE DESTINATION_COUNTRY = 'CAN' AND CLEARANCE_STATUS = 'REJECTED';

SELECT 
    DESTINATION_COUNTRY AS DEST_COUNTRY,
    COUNT_IF(CLEARANCE_STATUS = 'CLEARED') AS CLEARED_COUNT,
    COUNT_IF(CLEARANCE_STATUS = 'REJECTED') AS REJECTED_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY DESTINATION_COUNTRY
ORDER BY DESTINATION_COUNTRY;


-- END-TO-END PIPELINE LINEAGE & RECONCILIATION AUDIT
SELECT 
    (
        SELECT SUM(RAW_PAYLOAD:data.declared_value::NUMBER(12,2)) 
        FROM BRONZE_IOT_STREAMS 
        WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS'
    ) AS BRONZE_GROSS_TOTAL,
    (
        SELECT SUM(DECLARED_VALUE) 
        FROM SILVER_CUSTOMS_CLEARANCE
    ) AS SILVER_GROSS_TOTAL,
    (
        SELECT SUM(TOTAL_CLEARED_VAL) 
        FROM GOLD_COUNTRY_DUTY_SUMMARY
    ) AS GOLD_GROSS_TOTAL,
    CASE 
        WHEN (
            SELECT SUM(RAW_PAYLOAD:data.declared_value::NUMBER(12,2)) 
            FROM BRONZE_IOT_STREAMS 
            WHERE RAW_PAYLOAD:payload_type::VARCHAR = 'CUSTOMS'
        ) = (
            SELECT SUM(DECLARED_VALUE) 
            FROM SILVER_CUSTOMS_CLEARANCE
        ) 
        THEN TRUE 
        ELSE FALSE 
    END AS RECONCILED_FLAG;