
CREATE OR REPLACE WAREHOUSE SCD_ADV_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE RETAIL_SCD_ADV_DB;
CREATE OR REPLACE SCHEMA RETAIL_SCD_ADV_DB.SCD_HYBRID;

USE WAREHOUSE SCD_ADV_WH;
USE DATABASE RETAIL_SCD_ADV_DB;
USE SCHEMA SCD_HYBRID;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE SCD_STAGE
    FILE_FORMAT = CSV_FORMAT;


CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30));

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE);

COPY INTO STG_CUSTOMERS_INITIAL 
FROM @SCD_STAGE/customers_initial.csv 
FILE_FORMAT = CSV_FORMAT 
FORCE = TRUE;

COPY INTO STG_CUSTOMER_UPDATES 
FROM @SCD_STAGE/customers_updates.csv 
FILE_FORMAT = CSV_FORMAT 
ON_ERROR=CONTINUE;


-- REATE SCD TYPE 3 DIMENSION TABLE
CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD3 (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30));


-- LOAD INITIAL TYPE 3 DATA
INSERT INTO DIM_CUSTOMER_SCD3 (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, 
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, SEGMENT)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    STATE, 
    MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    NULL AS PREVIOUS_MEMBERSHIP, 
    SEGMENT
FROM STG_CUSTOMERS_INITIAL;


-- DISPLAY INITIAL TYPE 3 DATA
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
ORDER BY CUSTOMER_ID;


-- APPLY SCD TYPE 3 UPDATES 
MERGE INTO DIM_CUSTOMER_SCD3 target
USING STG_CUSTOMER_UPDATES source
ON target.CUSTOMER_ID = source.CUSTOMER_ID
WHEN MATCHED THEN
    UPDATE SET 
        target.PREVIOUS_MEMBERSHIP = target.CURRENT_MEMBERSHIP,
        target.CURRENT_MEMBERSHIP = source.MEMBERSHIP,
        target.CITY = source.CITY,
        target.STATE = source.STATE,
        target.SEGMENT = source.SEGMENT;


--  TYPE 3 FINAL REPORT
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
ORDER BY CUSTOMER_ID;


-- DEMONSTRATE TYPE 3 FOR CUSTOMER 101
SELECT CUSTOMER_ID, CUSTOMER_NAME, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD3
WHERE CUSTOMER_ID = 101;


--  CREATE SCD TYPE 6 DIMENSION TABLE
CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD6 (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN);


-- LOAD INITIAL TYPE 6 RECORDS
INSERT INTO DIM_CUSTOMER_SCD6 (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, 
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, 
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    STATE, 
    MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    NULL AS PREVIOUS_MEMBERSHIP, 
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP, 
    SEGMENT, 
    '2026-01-01'::DATE AS EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMERS_INITIAL;


-- APPLY TYPE 6 CHANGES (CUSTOMERS 101, 103, 104)
UPDATE DIM_CUSTOMER_SCD6 target
SET 
    target.EXPIRY_DATE = DATEADD(DAY, -1, source.EFFECTIVE_DATE),
    target.IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES source
WHERE target.CUSTOMER_ID = source.CUSTOMER_ID
  AND target.IS_CURRENT = TRUE;
INSERT INTO DIM_CUSTOMER_SCD6 (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, 
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, 
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    u.CUSTOMER_ID, 
    u.CUSTOMER_NAME, 
    u.CITY, 
    u.STATE, 
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    d.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP, 
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP, 
    u.SEGMENT, 
    u.EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_SCD6 d ON u.CUSTOMER_ID = d.CUSTOMER_ID AND d.IS_CURRENT = FALSE;


-- DISPLAY COMPLETE TYPE 6 HISTORY
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CURRENT_MEMBERSHIP, 
    PREVIOUS_MEMBERSHIP, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE, 
    IS_CURRENT
FROM DIM_CUSTOMER_SCD6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- CURRENT CUSTOMER REPORT
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    CURRENT_MEMBERSHIP, 
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_SCD6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


-- POINT-IN-TIME HISTORICAL QUERY (AS OF MARCH 15, 2026)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    HISTORICAL_MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE
FROM DIM_CUSTOMER_SCD6
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


-- TYPE 3 VS TYPE 6 COMPARISON MATRIX
SELECT 
    'SCD TYPE 3' AS STRATEGY,
    'YES' AS CURRENT_VALUE,
    'YES' AS PREVIOUS_VALUE,
    'NO' AS HISTORICAL_ROWS,
    'NO' AS EFFECTIVE_DATE,
    'NO' AS EXPIRY_DATE,
    'NO' AS IS_CURRENT
UNION ALL
SELECT 
    'SCD TYPE 6',
    'YES',
    'YES',
    'YES',
    'YES',
    'YES',
    'YES';


-- RECORD COUNT VALIDATION
SELECT 'SCD TYPE 3 RECORD COUNT' AS METRIC, COUNT(*) AS RECORD_COUNT 
FROM DIM_CUSTOMER_SCD3
UNION ALL
SELECT 'SCD TYPE 6 RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_SCD6
UNION ALL
SELECT 'SCD TYPE 6 CURRENT RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_SCD6 
WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'SCD TYPE 6 HISTORICAL RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_SCD6 
WHERE IS_CURRENT = FALSE;