
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE FINANCIAL_GOVERNANCE_DB;
CREATE OR REPLACE SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE;

USE DATABASE FINANCIAL_GOVERNANCE_DB;
USE SCHEMA WEALTH_CORE;


CREATE OR REPLACE FILE FORMAT RAW_TEXT_FF
    TYPE = 'CSV'
    RECORD_DELIMITER = '\n'
    FIELD_DELIMITER = 'NONE';

CREATE OR REPLACE STAGE BANKING_STAGE;


CREATE OR REPLACE TABLE STG_RAW_INPUT (
    RAW_LINE VARCHAR);


COPY INTO STG_RAW_INPUT 
FROM @BANKING_STAGE
FILE_FORMAT = RAW_TEXT_FF
PATTERN = '.*banking_batch.*[.]json'
FORCE = TRUE;


CREATE OR REPLACE TABLE BRONZE_BANK_PAYLOADS (
    INGEST_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());


INSERT INTO BRONZE_BANK_PAYLOADS (PAYLOAD)
SELECT PARSE_JSON(RAW_LINE)
FROM STG_RAW_INPUT
WHERE TRY_PARSE_JSON(RAW_LINE) IS NOT NULL 
  AND PARSE_JSON(RAW_LINE):txn_id IS NOT NULL;


SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_BANK_PAYLOADS;


CREATE OR REPLACE TABLE QUARANTINE_GOVERNANCE_PAYLOADS (
    QUARANTINE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RAW_RECORD_TEXT VARCHAR,
    REASON VARCHAR(100),
    QUARANTINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());


INSERT INTO QUARANTINE_GOVERNANCE_PAYLOADS (RAW_RECORD_TEXT, REASON)
SELECT 
    RAW_LINE,
    'MALFORMED_JSON_BODY' AS REASON
FROM STG_RAW_INPUT
WHERE TRY_PARSE_JSON(RAW_LINE) IS NULL 
   OR PARSE_JSON(RAW_LINE):txn_id IS NULL;


SELECT 
    QUARANTINE_ID,
    RAW_RECORD_TEXT,
    REASON
FROM QUARANTINE_GOVERNANCE_PAYLOADS;


--  SILVER LAYER SETUP & RBAC ROLE PROVISIONING
CREATE OR REPLACE TABLE SILVER_BANK_TRANSACTIONS (
    TXN_ID VARCHAR(30) PRIMARY KEY,
    CLIENT_ID NUMBER,
    CLIENT_SSN VARCHAR(30),
    REGION VARCHAR(10),
    ACCOUNT_NO VARCHAR(30),
    AMOUNT NUMBER(12,2),
    STATUS VARCHAR(20),
    AML_RISK_SCORE VARCHAR(20));


INSERT INTO SILVER_BANK_TRANSACTIONS (
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE)
SELECT 
    PAYLOAD:txn_id::VARCHAR AS TXN_ID,
    PAYLOAD:client_id::NUMBER AS CLIENT_ID,
    PAYLOAD:client_ssn::VARCHAR AS CLIENT_SSN,
    PAYLOAD:region::VARCHAR AS REGION,
    PAYLOAD:account_no::VARCHAR AS ACCOUNT_NO,
    PAYLOAD:amount::NUMBER(12,2) AS AMOUNT,
    PAYLOAD:status::VARCHAR AS STATUS,
    PAYLOAD:aml_risk_score::VARCHAR AS AML_RISK_SCORE
FROM BRONZE_BANK_PAYLOADS;


SELECT COUNT(*) AS TOTAL_SILVER_RECORDS FROM SILVER_BANK_TRANSACTIONS;

-- Provision RBAC Roles
CREATE OR REPLACE ROLE COMPLIANCE_OFFICER;
CREATE OR REPLACE ROLE NA_ANALYST;
CREATE OR REPLACE ROLE EU_ANALYST;


SET CURRENT_USER_NAME = CURRENT_USER();
GRANT ROLE COMPLIANCE_OFFICER TO USER IDENTIFIER($CURRENT_USER_NAME);
GRANT ROLE NA_ANALYST TO USER IDENTIFIER($CURRENT_USER_NAME);
GRANT ROLE EU_ANALYST TO USER IDENTIFIER($CURRENT_USER_NAME);

GRANT ROLE COMPLIANCE_OFFICER TO ROLE ACCOUNTADMIN;
GRANT ROLE NA_ANALYST TO ROLE ACCOUNTADMIN;
GRANT ROLE EU_ANALYST TO ROLE ACCOUNTADMIN;

-- Grant Database, Schema, Warehouse, and Table Privileges to all Roles
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NA_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE EU_ANALYST;

GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB TO ROLE NA_ANALYST;
GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB TO ROLE EU_ANALYST;

GRANT USAGE ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE TO ROLE NA_ANALYST;
GRANT USAGE ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE TO ROLE EU_ANALYST;

GRANT SELECT ON TABLE FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON TABLE FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS TO ROLE NA_ANALYST;
GRANT SELECT ON TABLE FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS TO ROLE EU_ANALYST;


-- ENTERPRISE GOVERNANCE VIA ROLE-AWARE SECURE VIEW
USE ROLE ACCOUNTADMIN;
USE DATABASE FINANCIAL_GOVERNANCE_DB;
USE SCHEMA WEALTH_CORE;

CREATE OR REPLACE SECURE VIEW V_SILVER_BANK_TRANSACTIONS AS
SELECT 
    TXN_ID,
    CLIENT_ID,
   
    CASE 
        WHEN CURRENT_ROLE() IN ('COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN CLIENT_SSN
        ELSE '***-**-' || RIGHT(CLIENT_SSN, 4)
    END AS CLIENT_SSN,
    REGION,
  
    CASE 
        WHEN CURRENT_ROLE() IN ('COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN ACCOUNT_NO
        ELSE LEFT(ACCOUNT_NO, 4) || '****'
    END AS ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM SILVER_BANK_TRANSACTIONS
WHERE 
    CURRENT_ROLE() IN ('COMPLIANCE_OFFICER', 'ACCOUNTADMIN')
    OR (CURRENT_ROLE() = 'NA_ANALYST' AND REGION = 'NA')
    OR (CURRENT_ROLE() = 'EU_ANALYST' AND REGION = 'EU');

GRANT SELECT ON VIEW V_SILVER_BANK_TRANSACTIONS TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON VIEW V_SILVER_BANK_TRANSACTIONS TO ROLE NA_ANALYST;
GRANT SELECT ON VIEW V_SILVER_BANK_TRANSACTIONS TO ROLE EU_ANALYST;


USE ROLE NA_ANALYST;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCIAL_GOVERNANCE_DB;
USE SCHEMA WEALTH_CORE;

SELECT 
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM V_SILVER_BANK_TRANSACTIONS
ORDER BY TXN_ID;


-- SECURE DATA SHARING & CLEAN ROOM AUDIT VIEW
USE ROLE ACCOUNTADMIN;
USE DATABASE FINANCIAL_GOVERNANCE_DB;
USE SCHEMA WEALTH_CORE;

CREATE OR REPLACE SECURE VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY AS
SELECT 
    REGION,
    SUM(AMOUNT) AS TOTAL_SETTLED_VAL,
    COUNT(*) AS SETTLED_TXN_COUNT,
    ROUND(AVG(AMOUNT), 2) AS AVG_SETTLED_AMOUNT
FROM SILVER_BANK_TRANSACTIONS
WHERE STATUS = 'SETTLED'
GROUP BY REGION;

GRANT SELECT ON VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY TO ROLE NA_ANALYST;
GRANT SELECT ON VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY TO ROLE EU_ANALYST;

-- Task 5 Verification Query (Executed as ACCOUNTADMIN or COMPLIANCE_OFFICER)
SELECT 
    REGION,
    TOTAL_SETTLED_VAL,
    SETTLED_TXN_COUNT,
    AVG_SETTLED_AMOUNT
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
ORDER BY REGION;


-- END-TO-END GOVERNANCE AUDIT & LINEAGE RECONCILIATION
USE ROLE COMPLIANCE_OFFICER;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCIAL_GOVERNANCE_DB;
USE SCHEMA WEALTH_CORE;

SELECT 
    (
        SELECT SUM(PAYLOAD:amount::NUMBER(12,2)) 
        FROM BRONZE_BANK_PAYLOADS
    ) AS BRONZE_GROSS_TOTAL,
    (
        SELECT SUM(AMOUNT) 
        FROM SILVER_BANK_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,
    (
        SELECT SUM(TOTAL_SETTLED_VAL) 
        FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
    ) AS GOLD_GROSS_TOTAL,
    CASE 
        WHEN (
            SELECT SUM(PAYLOAD:amount::NUMBER(12,2)) 
            FROM BRONZE_BANK_PAYLOADS
        ) = (
            SELECT SUM(AMOUNT) 
            FROM SILVER_BANK_TRANSACTIONS
        )
        THEN TRUE 
        ELSE FALSE 
    END AS RECONCILED_FLAG;