
CREATE OR REPLACE WAREHOUSE HEALTHCARE_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE HEALTHCARE_DW;
CREATE OR REPLACE SCHEMA HEALTHCARE_DW.HEALTHCARE_SCHEMA;

USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DW;
USE SCHEMA HEALTHCARE_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE HEALTHCARE_STAGE
    FILE_FORMAT = CSV_FORMAT;


--CREATE DIMENSION TABLES (WITH SURROGATE KEYS)
CREATE OR REPLACE TABLE DIM_PATIENT (PATIENT_KEY INT AUTOINCREMENT PRIMARY KEY,PATIENT_ID VARCHAR(20) UNIQUE,PATIENT_NAME VARCHAR(100),GENDER VARCHAR(10),
CITY VARCHAR(50),STATE VARCHAR(50));

CREATE OR REPLACE TABLE DIM_DOCTOR (DOCTOR_KEY INT AUTOINCREMENT PRIMARY KEY,DOCTOR_ID VARCHAR(20) UNIQUE,DOCTOR_NAME VARCHAR(100),SPECIALIZATION VARCHAR(50));

CREATE OR REPLACE TABLE DIM_HOSPITAL (HOSPITAL_KEY INT AUTOINCREMENT PRIMARY KEY,HOSPITAL_ID VARCHAR(20) UNIQUE,HOSPITAL_NAME VARCHAR(100),CITY VARCHAR(50),
STATE VARCHAR(50),REGION VARCHAR(50));

CREATE OR REPLACE TABLE DIM_DEPARTMENT (DEPARTMENT_KEY INT AUTOINCREMENT PRIMARY KEY,DEPARTMENT_ID VARCHAR(20) UNIQUE,DEPARTMENT_NAME VARCHAR(100));

CREATE OR REPLACE TABLE DIM_TREATMENT (TREATMENT_KEY INT AUTOINCREMENT PRIMARY KEY,TREATMENT_ID VARCHAR(20) UNIQUE,TREATMENT_NAME VARCHAR(100),TREATMENT_CATEGORY VARCHAR(50));



CREATE OR REPLACE TABLE STG_PATIENTS (PATIENT_ID VARCHAR(20),PATIENT_NAME VARCHAR(100),GENDER VARCHAR(10),CITY VARCHAR(50),STATE VARCHAR(50));

CREATE OR REPLACE TABLE STG_DOCTORS (DOCTOR_ID VARCHAR(20),DOCTOR_NAME VARCHAR(100),SPECIALIZATION VARCHAR(50));

CREATE OR REPLACE TABLE STG_HOSPITALS (HOSPITAL_ID VARCHAR(20),HOSPITAL_NAME VARCHAR(100),CITY VARCHAR(50),STATE VARCHAR(50),REGION VARCHAR(50));

CREATE OR REPLACE TABLE STG_DEPARTMENTS (DEPARTMENT_ID VARCHAR(20),DEPARTMENT_NAME VARCHAR(100));

CREATE OR REPLACE TABLE STG_TREATMENTS (TREATMENT_ID VARCHAR(20),TREATMENT_NAME VARCHAR(100),TREATMENT_CATEGORY VARCHAR(50));


COPY INTO STG_PATIENTS FROM @HEALTHCARE_STAGE/patients.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;
COPY INTO STG_DOCTORS FROM @HEALTHCARE_STAGE/doctors.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;
COPY INTO STG_HOSPITALS FROM @HEALTHCARE_STAGE/hospitals.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;
COPY INTO STG_DEPARTMENTS FROM @HEALTHCARE_STAGE/departments.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;
COPY INTO STG_TREATMENTS FROM @HEALTHCARE_STAGE/treatments.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;


INSERT INTO DIM_PATIENT (PATIENT_ID, PATIENT_NAME, GENDER, CITY, STATE)
SELECT PATIENT_ID, PATIENT_NAME, GENDER, CITY, STATE FROM STG_PATIENTS;

INSERT INTO DIM_DOCTOR (DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION)
SELECT DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION FROM STG_DOCTORS;

INSERT INTO DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, REGION)
SELECT HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, REGION FROM STG_HOSPITALS;

INSERT INTO DIM_DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM STG_DEPARTMENTS;

INSERT INTO DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, TREATMENT_CATEGORY)
SELECT TREATMENT_ID, TREATMENT_NAME, TREATMENT_CATEGORY FROM STG_TREATMENTS;


-- CREATE DIM_DATE (2026-01-01 to 2026-03-31)
CREATE OR REPLACE TABLE DIM_DATE (DATE_KEY INT PRIMARY KEY,FULL_DATE DATE,DAY INT,DAY_NAME VARCHAR(20),WEEK_NO INT,MONTH INT,MONTH_NAME VARCHAR(20),
QUARTER VARCHAR(10),YEAR INT);

INSERT INTO DIM_DATE
WITH DATE_GENERATOR AS (SELECT DATEADD(DAY, SEQ4(), '2026-01-01'::DATE) AS DT
    FROM TABLE(GENERATOR(ROWCOUNT => 90)))
SELECT 
    TO_NUMBER(TO_VARCHAR(DT, 'YYYYMMDD')) AS DATE_KEY,
    DT AS FULL_DATE,
    DAY(DT) AS DAY,
    DAYNAME(DT) AS DAY_NAME,
    WEEK(DT) AS WEEK_NO,
    MONTH(DT) AS MONTH,
    MONTHNAME(DT) AS MONTH_NAME,
    'Q' || QUARTER(DT) AS QUARTER,
    YEAR(DT) AS YEAR
FROM DATE_GENERATOR
WHERE DT <= '2026-03-31';


-- FACT_ADMISSION
CREATE OR REPLACE TABLE STG_ADMISSIONS (ADMISSION_ID VARCHAR(20),PATIENT_ID VARCHAR(20),DOCTOR_ID VARCHAR(20),HOSPITAL_ID VARCHAR(20),DEPARTMENT_ID VARCHAR(20),
ADMISSION_DATE DATE,DISCHARGE_DATE DATE);

COPY INTO STG_ADMISSIONS FROM @HEALTHCARE_STAGE/admissions.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;

CREATE OR REPLACE TABLE FACT_ADMISSION (ADMISSION_KEY INT AUTOINCREMENT PRIMARY KEY,ADMISSION_ID VARCHAR(20),PATIENT_KEY INT,DOCTOR_KEY INT,
HOSPITAL_KEY INT,DEPARTMENT_KEY INT,DATE_KEY INT,ADMISSION_COUNT INT DEFAULT 1,LENGTH_OF_STAY INT,
FOREIGN KEY (PATIENT_KEY) REFERENCES DIM_PATIENT(PATIENT_KEY),
FOREIGN KEY (DOCTOR_KEY) REFERENCES DIM_DOCTOR(DOCTOR_KEY),
FOREIGN KEY (HOSPITAL_KEY) REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),
FOREIGN KEY (DEPARTMENT_KEY) REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY));

INSERT INTO FACT_ADMISSION (
    ADMISSION_ID, PATIENT_KEY, DOCTOR_KEY, HOSPITAL_KEY, 
    DEPARTMENT_KEY, DATE_KEY, ADMISSION_COUNT, LENGTH_OF_STAY)
SELECT 
    a.ADMISSION_ID,
    p.PATIENT_KEY,
    d.DOCTOR_KEY,
    h.HOSPITAL_KEY,
    dp.DEPARTMENT_KEY,
    dt.DATE_KEY,
    1 AS ADMISSION_COUNT,
    DATEDIFF(DAY, a.ADMISSION_DATE, a.DISCHARGE_DATE) AS LENGTH_OF_STAY
FROM STG_ADMISSIONS a
JOIN DIM_PATIENT p ON a.PATIENT_ID = p.PATIENT_ID
JOIN DIM_DOCTOR d ON a.DOCTOR_ID = d.DOCTOR_ID
JOIN DIM_HOSPITAL h ON a.HOSPITAL_ID = h.HOSPITAL_ID
JOIN DIM_DEPARTMENT dp ON a.DEPARTMENT_ID = dp.DEPARTMENT_ID
JOIN DIM_DATE dt ON a.ADMISSION_DATE = dt.FULL_DATE;


--FACT_BILLING
CREATE OR REPLACE TABLE STG_BILLING (BILL_ID VARCHAR(20),ADMISSION_ID VARCHAR(20),PATIENT_ID VARCHAR(20),DOCTOR_ID VARCHAR(20),HOSPITAL_ID VARCHAR(20),
DEPARTMENT_ID VARCHAR(20),TREATMENT_ID VARCHAR(20),BILL_DATE DATE,QUANTITY INT,TREATMENT_AMOUNT DECIMAL(15,2),DISCOUNT DECIMAL(15,2));

COPY INTO STG_BILLING FROM @HEALTHCARE_STAGE/billings.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;

CREATE OR REPLACE TABLE FACT_BILLING (BILLING_KEY INT AUTOINCREMENT PRIMARY KEY,BILL_ID VARCHAR(20),PATIENT_KEY INT,DOCTOR_KEY INT,HOSPITAL_KEY INT,
DEPARTMENT_KEY INT,TREATMENT_KEY INT,DATE_KEY INT,QUANTITY INT,TREATMENT_AMOUNT DECIMAL(15,2),DISCOUNT DECIMAL(15,2),NET_AMOUNT DECIMAL(15,2),
FOREIGN KEY (PATIENT_KEY) REFERENCES DIM_PATIENT(PATIENT_KEY),
FOREIGN KEY (DOCTOR_KEY) REFERENCES DIM_DOCTOR(DOCTOR_KEY),
FOREIGN KEY (HOSPITAL_KEY) REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),
FOREIGN KEY (DEPARTMENT_KEY) REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),
FOREIGN KEY (TREATMENT_KEY) REFERENCES DIM_TREATMENT(TREATMENT_KEY),
FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY));

INSERT INTO FACT_BILLING (BILL_ID, PATIENT_KEY, DOCTOR_KEY, HOSPITAL_KEY, 
DEPARTMENT_KEY, TREATMENT_KEY, DATE_KEY, QUANTITY, TREATMENT_AMOUNT, DISCOUNT, NET_AMOUNT)
SELECT 
    b.BILL_ID,p.PATIENT_KEY,d.DOCTOR_KEY,h.HOSPITAL_KEY,dp.DEPARTMENT_KEY,t.TREATMENT_KEY,dt.DATE_KEY,b.QUANTITY,b.TREATMENT_AMOUNT,b.DISCOUNT,(b.TREATMENT_AMOUNT - b.DISCOUNT) AS NET_AMOUNT FROM STG_BILLING b
JOIN DIM_PATIENT p ON b.PATIENT_ID = p.PATIENT_ID
JOIN DIM_DOCTOR d ON b.DOCTOR_ID = d.DOCTOR_ID
JOIN DIM_HOSPITAL h ON b.HOSPITAL_ID = h.HOSPITAL_ID
JOIN DIM_DEPARTMENT dp ON b.DEPARTMENT_ID = dp.DEPARTMENT_ID
JOIN DIM_TREATMENT t ON b.TREATMENT_ID = t.TREATMENT_ID
JOIN DIM_DATE dt ON b.BILL_DATE = dt.FULL_DATE;



-- ADMISSION ANALYTICS
SELECT h.HOSPITAL_NAME,SUM(fa.ADMISSION_COUNT) AS TOTAL_ADMISSIONS
FROM FACT_ADMISSION fa JOIN DIM_HOSPITAL h ON fa.HOSPITAL_KEY = h.HOSPITAL_KEY
GROUP BY h.HOSPITAL_NAME
ORDER BY TOTAL_ADMISSIONS DESC;


-- HOSPITAL REVENUE ANALYTICS
SELECT h.HOSPITAL_NAME,SUM(fb.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING fb
JOIN DIM_HOSPITAL h ON fb.HOSPITAL_KEY = h.HOSPITAL_KEY
GROUP BY h.HOSPITAL_NAME
ORDER BY TOTAL_REVENUE DESC;


-- MONTHLY REVENUE
SELECT TO_VARCHAR(d.FULL_DATE, 'YYYY-MM') AS MONTH,SUM(fb.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING fb
JOIN DIM_DATE d ON fb.DATE_KEY = d.DATE_KEY
GROUP BY TO_VARCHAR(d.FULL_DATE, 'YYYY-MM')
ORDER BY MONTH;


-- DOCTOR-WISE REVENUE
SELECT doc.DOCTOR_NAME AS DOCTOR,SUM(fb.NET_AMOUNT) AS TOTAL_REVENUE
FROM FACT_BILLING fb
JOIN DIM_DOCTOR doc ON fb.DOCTOR_KEY = doc.DOCTOR_KEY
GROUP BY doc.DOCTOR_NAME
ORDER BY TOTAL_REVENUE DESC;


-- DRILL-ACROSS ANALYSIS
WITH ADMISSION_METRICS AS (
    SELECT HOSPITAL_KEY,SUM(ADMISSION_COUNT) AS TOTAL_ADMISSIONS
    FROM FACT_ADMISSION
    GROUP BY HOSPITAL_KEY),
BILLING_METRICS AS (
    SELECT HOSPITAL_KEY,SUM(NET_AMOUNT) AS TOTAL_REVENUE
    FROM FACT_BILLING
    GROUP BY HOSPITAL_KEY)
SELECT h.HOSPITAL_NAME,a.TOTAL_ADMISSIONS,b.TOTAL_REVENUE
FROM DIM_HOSPITAL h
LEFT JOIN ADMISSION_METRICS a ON h.HOSPITAL_KEY = a.HOSPITAL_KEY
LEFT JOIN BILLING_METRICS b ON h.HOSPITAL_KEY = b.HOSPITAL_KEY
ORDER BY b.TOTAL_REVENUE DESC;