
CREATE OR REPLACE DATABASE RETAIL_DW;
CREATE OR REPLACE SCHEMA RETAIL_DW.SALES_ANALYTICS;

USE DATABASE RETAIL_DW;
USE SCHEMA SALES_ANALYTICS;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE RETAIL_STAGE
    FILE_FORMAT = CSV_FORMAT;


CREATE OR REPLACE TABLE STG_STORES (
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100));

CREATE OR REPLACE TABLE STG_PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2));

CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30));

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE);


COPY INTO STG_STORES FROM @RETAIL_STAGE/stores.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;
COPY INTO STG_PRODUCTS FROM @RETAIL_STAGE/products.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;
COPY INTO STG_CUSTOMERS_INITIAL FROM @RETAIL_STAGE/customers_initial.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;
COPY INTO STG_CUSTOMER_UPDATES FROM @RETAIL_STAGE/customers_updates.csv FILE_FORMAT = CSV_FORMAT ON_ERROR=CONTINUE;



CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100));



CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2));


CREATE OR REPLACE TABLE DIM_CUSTOMER_HYBRID (
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN);


INSERT INTO DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER)
SELECT STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER 
FROM STG_STORES;

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE)
SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE 
FROM STG_PRODUCTS;



INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, 
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, 
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    NULL AS PREVIOUS_CITY, 
    STATE, 
    MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    NULL AS PREVIOUS_MEMBERSHIP, 
    MEMBERSHIP AS HISTORICAL_MEMBERSHIP, 
    SEGMENT, 
    '2026-01-01'::DATE AS EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMERS_INITIAL;


CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_KEY NUMBER,
    STORE_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(12,2),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY));


-- 1. TXN-1001: Customer 101, Product 501, Store 201, Date: 2026-02-15
INSERT INTO FACT_SALES (
    TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT 
    'TXN-1001',
    '2026-02-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    (1 * p.UNIT_PRICE)
FROM DIM_CUSTOMER_HYBRID c
CROSS JOIN DIM_STORE s
CROSS JOIN DIM_PRODUCT p
WHERE c.CUSTOMER_ID = 101 AND c.IS_CURRENT = TRUE
  AND s.STORE_ID = 201
  AND p.PRODUCT_ID = 501;

-- 2. TXN-1002: Customer 103, Product 502, Store 203, Date: 2026-03-10
INSERT INTO FACT_SALES (
    TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT 
    'TXN-1002',
    '2026-03-10'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    2,
    p.UNIT_PRICE,
    (2 * p.UNIT_PRICE)
FROM DIM_CUSTOMER_HYBRID c
CROSS JOIN DIM_STORE s
CROSS JOIN DIM_PRODUCT p
WHERE c.CUSTOMER_ID = 103 AND c.IS_CURRENT = TRUE
  AND s.STORE_ID = 203
  AND p.PRODUCT_ID = 502;


UPDATE DIM_STORE
SET STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

SELECT STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER 
FROM DIM_STORE 
WHERE STORE_ID = 201;



UPDATE DIM_CUSTOMER_HYBRID target
SET 
    target.EXPIRY_DATE = DATEADD(DAY, -1, source.EFFECTIVE_DATE),
    target.IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES source
WHERE target.CUSTOMER_ID = source.CUSTOMER_ID
  AND target.IS_CURRENT = TRUE;


INSERT INTO DIM_CUSTOMER_HYBRID (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, 
    CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, 
    SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    u.CUSTOMER_ID, 
    u.CUSTOMER_NAME, 
    u.CITY, 
    d.CITY AS PREVIOUS_CITY, 
    u.STATE, 
    u.MEMBERSHIP AS CURRENT_MEMBERSHIP, 
    d.HISTORICAL_MEMBERSHIP AS PREVIOUS_MEMBERSHIP, 
    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP, 
    u.SEGMENT, 
    u.EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMER_UPDATES u
JOIN DIM_CUSTOMER_HYBRID d ON u.CUSTOMER_ID = d.CUSTOMER_ID AND d.IS_CURRENT = FALSE;


UPDATE DIM_CUSTOMER_HYBRID 
SET CITY = 'Bengaluru', PREVIOUS_CITY = 'Hyderabad', STATE = 'Karnataka', CURRENT_MEMBERSHIP = 'Gold', PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID 
SET CITY = 'Chennai', PREVIOUS_CITY = 'Vijayawada', STATE = 'Tamil Nadu', CURRENT_MEMBERSHIP = 'Gold', PREVIOUS_MEMBERSHIP = 'Silver'
WHERE CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID 
SET CURRENT_MEMBERSHIP = 'Platinum', PREVIOUS_MEMBERSHIP = 'Gold'
WHERE CUSTOMER_ID = 104;



INSERT INTO FACT_SALES (
    TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT 
    'TXN-2001',
    '2026-04-15'::DATE,
    c.CUSTOMER_KEY,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    1,
    p.UNIT_PRICE,
    (1 * p.UNIT_PRICE)
FROM DIM_CUSTOMER_HYBRID c
CROSS JOIN DIM_STORE s
CROSS JOIN DIM_PRODUCT p
WHERE c.CUSTOMER_ID = 101 AND c.IS_CURRENT = TRUE
  AND s.STORE_ID = 201
  AND p.PRODUCT_ID = 503;


SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;



SELECT 
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY AS CURRENT_CITY,
    c.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    c.SEGMENT AS SEGMENT_AT_PURCHASE,
    s.STORE_NAME,
    p.PRODUCT_NAME,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_CUSTOMER_HYBRID c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_STORE s ON f.STORE_KEY = s.STORE_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
WHERE c.CUSTOMER_ID = 101
ORDER BY f.TRANSACTION_DATE;


--WAREHOUSE RECORD COUNT AND DATA AUDITING VALIDATION
SELECT 'STORE DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_STORE
UNION ALL
SELECT 'PRODUCT DIMENSION RECORDS', COUNT(*) FROM DIM_PRODUCT
UNION ALL
SELECT 'TOTAL CUSTOMER DIMENSION RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID
UNION ALL
SELECT 'CURRENT CUSTOMER RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL CUSTOMER RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = FALSE
UNION ALL
SELECT 'FACT SALES TRANSACTIONS', COUNT(*) FROM FACT_SALES;