
CREATE OR REPLACE WAREHOUSE SCD_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE RETAIL_SCD_DB;
CREATE OR REPLACE SCHEMA RETAIL_SCD_DB.SCD_MANAGEMENT;

USE WAREHOUSE SCD_WH;
USE DATABASE RETAIL_SCD_DB;
USE SCHEMA SCD_MANAGEMENT;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE SCD_STAGE
    FILE_FORMAT = CSV_FORMAT;



CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30));

CREATE OR REPLACE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE);

COPY INTO STG_CUSTOMERS_INITIAL 
FROM @SCD_STAGE/customers_initial.csv 
FILE_FORMAT = CSV_FORMAT 
FORCE = TRUE;

COPY INTO STG_CUSTOMER_UPDATES 
FROM @SCD_STAGE/customer_updates.csv 
FILE_FORMAT = CSV_FORMAT 
FORCE = TRUE;


--CREATE SCD TYPE 1 TABLE
CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD1 (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30));


--  LOAD INITIAL TYPE 1 DATA
INSERT INTO DIM_CUSTOMER_SCD1 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT 
FROM STG_CUSTOMERS_INITIAL;


-- APPLY SCD TYPE 1 UPDATES 
MERGE INTO DIM_CUSTOMER_SCD1 target
USING STG_CUSTOMER_UPDATES source
ON target.CUSTOMER_ID = source.CUSTOMER_ID
WHEN MATCHED THEN
    UPDATE SET 
        target.CUSTOMER_NAME = source.CUSTOMER_NAME,
        target.CITY = source.CITY,
        target.STATE = source.STATE,
        target.MEMBERSHIP = source.MEMBERSHIP,
        target.SEGMENT = source.SEGMENT;


-- DISPLAY TYPE 1 RESULT
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER_SCD1
ORDER BY CUSTOMER_ID;


--  DEMONSTRATE TYPE 1 HISTORY LOSS
SELECT CUSTOMER_ID, CITY, STATE, MEMBERSHIP
FROM DIM_CUSTOMER_SCD1
WHERE CUSTOMER_ID = 101;


-- CREATE SCD TYPE 2 TABLE
CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD2 (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN);

DESCRIBE TABLE DIM_CUSTOMER_SCD2;


-- LOAD INITIAL TYPE 2 RECORDS
INSERT INTO DIM_CUSTOMER_SCD2 (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, 
    MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    STATE, 
    MEMBERSHIP, 
    SEGMENT, 
    '2026-01-01'::DATE AS EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMERS_INITIAL;


-- APPLY TYPE 2 CHANGES (EXPIRE OLD & INSERT NEW VERSION)
-- Step 1: Expire the existing active records
UPDATE DIM_CUSTOMER_SCD2 target
SET 
    target.EXPIRY_DATE = DATEADD(DAY, -1, source.EFFECTIVE_DATE),
    target.IS_CURRENT = FALSE
FROM STG_CUSTOMER_UPDATES source
WHERE target.CUSTOMER_ID = source.CUSTOMER_ID
  AND target.IS_CURRENT = TRUE;


INSERT INTO DIM_CUSTOMER_SCD2 (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, 
    MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    source.CUSTOMER_ID, 
    source.CUSTOMER_NAME, 
    source.CITY, 
    source.STATE, 
    source.MEMBERSHIP, 
    source.SEGMENT, 
    source.EFFECTIVE_DATE, 
    '9999-12-31'::DATE AS EXPIRY_DATE, 
    TRUE AS IS_CURRENT
FROM STG_CUSTOMER_UPDATES source;


-- CUSTOMER 101 TYPE 2 CHANGE VERIFICATION
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;


-- CUSTOMER 103 TYPE 2 CHANGE VERIFICATION
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;


--  CUSTOMER 104 TYPE 2 CHANGE VERIFICATION
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;


-- DISPLAY COMPLETE TYPE 2 HISTORY
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    CITY, 
    STATE, 
    MEMBERSHIP, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE, 
    IS_CURRENT
FROM DIM_CUSTOMER_SCD2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


--  DISPLAY CURRENT CUSTOMER RECORDS
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT
FROM DIM_CUSTOMER_SCD2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


--HISTORICAL CUSTOMER ANALYSIS (AS OF MARCH 15, 2026)
SELECT 
    CUSTOMER_ID, 
    CUSTOMER_NAME, 
    MEMBERSHIP, 
    CITY, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


-- COMPARE TYPE 1 VS TYPE 2 
SELECT 
    'SCD TYPE 1' AS STRATEGY,
    'Overwritten' AS OLD_VALUE,
    'Not Preserved' AS HISTORY,
    'No' AS NEW_ROW,
    'No' AS EFFECTIVE_DATE_TRACKING,
    'No' AS EXPIRY_DATE_TRACKING,
    'No' AS IS_CURRENT_FLAG,
    'Lower' AS STORAGE_REQUIREMENT
UNION ALL
SELECT 
    'SCD TYPE 2',
    'Preserved',
    'Preserved',
    'Yes',
    'Yes',
    'Yes',
    'Yes',
    'Higher';


-- FINAL VALIDATION & RECORD COUNTS
SELECT 'SCD TYPE 1 RECORD COUNT' AS METRIC, COUNT(*) AS TOTAL_COUNT 
FROM DIM_CUSTOMER_SCD1
UNION ALL
SELECT 'SCD TYPE 2 RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_SCD2
UNION ALL
SELECT 'SCD TYPE 2 CURRENT RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_SCD2 
WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'SCD TYPE 2 HISTORICAL RECORD COUNT', COUNT(*) 
FROM DIM_CUSTOMER_SCD2 
WHERE IS_CURRENT = FALSE;