
CREATE OR REPLACE WAREHOUSE SCD_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE SCD_DEMO_DB;
CREATE OR REPLACE SCHEMA SCD_DEMO_DB.SCD_SCHEMA;

USE WAREHOUSE SCD_WH;
USE DATABASE SCD_DEMO_DB;
USE SCHEMA SCD_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE SCD_STAGE
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50));


CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIAL (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50));

COPY INTO STG_CUSTOMERS_INITIAL FROM @SCD_STAGE/customers_initial.csv FILE_FORMAT = CSV_FORMAT FORCE = TRUE;

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT 
FROM STG_CUSTOMERS_INITIAL;


SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;



CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50));

COPY INTO CUSTOMER_UPDATES 
FROM @SCD_STAGE/customers_updates.csv 
FILE_FORMAT = CSV_FORMAT 
FORCE = TRUE;

SELECT * FROM CUSTOMER_UPDATES ORDER BY CUSTOMER_ID;


-- IDENTIFY CHANGED CUSTOMERS
SELECT 
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY != u.CITY 
   OR d.STATE != u.STATE 
   OR d.MEMBERSHIP != u.MEMBERSHIP 
   OR d.SEGMENT != u.SEGMENT
ORDER BY d.CUSTOMER_ID;


-- IDENTIFY ATTRIBUTE CHANGES 
SELECT CUSTOMER_ID, 'CITY' AS ATTRIBUTE, OLD_CITY AS OLD_VALUE, NEW_CITY AS NEW_VALUE
FROM (
    SELECT d.CUSTOMER_ID, d.CITY AS OLD_CITY, u.CITY AS NEW_CITY
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.CITY != u.CITY
)
UNION ALL
SELECT CUSTOMER_ID, 'STATE' AS ATTRIBUTE, OLD_STATE AS OLD_VALUE, NEW_STATE AS NEW_VALUE
FROM (
    SELECT d.CUSTOMER_ID, d.STATE AS OLD_STATE, u.STATE AS NEW_STATE
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.STATE != u.STATE
)
UNION ALL
SELECT CUSTOMER_ID, 'MEMBERSHIP' AS ATTRIBUTE, OLD_MEMBERSHIP AS OLD_VALUE, NEW_MEMBERSHIP AS NEW_VALUE
FROM (
    SELECT d.CUSTOMER_ID, d.MEMBERSHIP AS OLD_MEMBERSHIP, u.MEMBERSHIP AS NEW_MEMBERSHIP
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.MEMBERSHIP != u.MEMBERSHIP
)
UNION ALL
SELECT CUSTOMER_ID, 'SEGMENT' AS ATTRIBUTE, OLD_SEGMENT AS OLD_VALUE, NEW_SEGMENT AS NEW_VALUE
FROM (
    SELECT d.CUSTOMER_ID, d.SEGMENT AS OLD_SEGMENT, u.SEGMENT AS NEW_SEGMENT
    FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
    WHERE d.SEGMENT != u.SEGMENT
)
ORDER BY CUSTOMER_ID, ATTRIBUTE;


-- DEMONSTRATE THE SCD PROBLEM (OVERWRITE EXISTING ROWS - SCD TYPE 1)
UPDATE DIM_CUSTOMER d
SET 
    d.CITY = u.CITY,
    d.STATE = u.STATE,
    d.MEMBERSHIP = u.MEMBERSHIP,
    d.SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


-- DISPLAY THE UPDATED DIMENSION
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT 
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;



-- DEMONSTRATE HISTORICAL DATA LOSS
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP 
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;


-- BUSINESS IMPACT ANALYSIS 
SELECT 
    '101' AS CUSTOMER_ID,
    'Hyderabad' AS ORIGINAL_CITY,
    CITY AS CURRENT_CITY,
    'Silver' AS ORIGINAL_MEMBERSHIP,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    'LOST' AS HISTORICAL_CITY_STATUS,
    'LOST' AS HISTORICAL_STATE_STATUS,
    'LOST' AS HISTORICAL_MEMBERSHIP_STATUS
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;